name: Mirror to Codeberg

on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror repository to Codeberg
        uses: yesolutions/mirror-action@v0.7.0
        with:
          REMOTE: git@codeberg.org:WilliamWei/WiIIiamWei.github.io.git
          GIT_SSH_PRIVATE_KEY: ${{ secrets.CODEBERG_SSH_PRIVATE_KEY }}
          GIT_SSH_KNOWN_HOSTS: ${{ secrets.CODEBERG_KNOWN_HOSTS }}
